name: Send Baby Vaccine Notifications

on:
  schedule:
    - cron: "0 9 * * *"  # runs every day at 9 AM UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    env: 
      FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin

      - name: Run notification script
        run: python baby_notifications/send_notifications.py
