name: Send Baby Vaccine Notifications

on:
  schedule:
     - cron: '15 1 * * *' # runs every day at 9:00 AM UTC
  workflow_dispatch: # allows manual run

jobs:
  send_notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install firebase-admin

      - name: List files (debug)
        run: ls -R

      - name: Run notifications
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python send_notifications.py
