name: Send Baby Vaccine Notifications

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes UTC
  workflow_dispatch: # Allows manual run

jobs:
  send_notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install firebase-admin

      - name: Debug - Print PH date/time
        run: |
          echo "Workflow triggered!"
          echo "UTC time: $(date -u)"
          echo "PH time (UTC+8): $(date -u -d '+8 hours')"

      - name: List files (debug)
        run: ls -R

      - name: Run notifications
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python send_notifications.py
