name: Test Workflow

on:
  workflow_dispatch:   # allows manual trigger


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "GitHub Actions is working!"
          echo "UTC time: $(date -u)"
          echo "PH time (UTC+8): $(date -u -d '+8 hours')"
